"""GEO Agent domain model package."""

from .answer_provider import (
    AnswerCredentialRef,
    AnswerProviderConfig,
    AnswerProviderRequest,
    OpenAICompatibleAnswerProvider,
)
from .artifact_safety import (
    ArtifactSafetyFinding,
    ArtifactSafetyReport,
    assert_artifacts_safe,
    scan_artifacts_for_access_leaks,
)
from .audit_runner import AuditArtifacts, AuditRunner
from .browser_capture import (
    BrowserCaptureArtifact,
    BrowserCaptureError,
    BrowserCaptureRecord,
    BrowserViewport,
    artifact_digest,
    make_capture_artifact,
)
from .citation_absorption import CitationAbsorptionMetric, calculate_citation_absorption, calculate_citation_absorption_from_urls
from .citation_parser import CitationParserError, ParsedCitation, citation_domain, normalize_citation_url, parse_citations
from .claim_fidelity import ClaimFidelityResult, audit_claim_fidelity, audit_claims_fidelity
from .crawl_provider import (
    CrawlProviderError,
    CrawlProviderRequest,
    CrawlProviderResult,
    StaticCrawlerProvider,
    pages_from_crawl_result,
)
from .crawl_provider_v2 import (
    CrawlerProviderV2Request,
    CrawlerProviderV2Result,
    PageCrawlResult,
    StaticCrawlerProviderV2,
)
from .entity_profile import (
    EntityProfile,
    EntityProfileValidationError,
    ValidationIssue,
    validate_entity_profile,
)
from .evidence_store import EvidenceStore, ReportArtifact
from .failure_debugger import FailureDiagnosis, diagnose_failure_v2
from .fixture_package import FixturePackageResult, run_fixture_package
from .learning_records import (
    OptimizationOutcomeRecord,
    OptimizationOutcomeSummary,
    recommended_learning_actions,
    summarize_outcomes,
)
from .manual_import import ManualImportError, ManualImportResult, validate_manual_import
from .page_snapshot_extractor import (
    ExtractedFAQ,
    ExtractedPageSnapshot,
    ExtractedTable,
    PageSnapshotExtractionError,
    extract_page_snapshot,
)
from .provider_access import (
    ApiKeySession,
    ApiKeySessionStore,
    ProviderAccessError,
    ProviderConnection,
    ProviderDefinition,
    ProviderRegistry,
    default_provider_registry,
    redact_credential_label,
)
from .provider_auth_flow import (
    AuthorizationSessionStore,
    AuthorizationStart,
    FakeAuthorizationProvider,
    TokenSession,
)
from .provider_output_eval import (
    ProviderOutputEvalCase,
    ProviderOutputEvalResult,
    ProviderOutputEvalSummary,
    evaluate_provider_output_cases,
    provider_response_to_run,
)
from .provider_status_copy import ProviderStatusCopy, provider_report_status_line, provider_status_copy
from .providers import ManualImportProvider, ManualImportProviderRequest, ManualImportProviderResult
from .query_space import INTENT_TYPES, QueryRecord, build_query_space
from .recorded_dataset import (
    RecordedAuditDataset,
    RecordedDatasetError,
    load_recorded_dataset,
    load_recorded_dataset_from_mapping,
)
from .retest_planning import RetestComparison, RetestMetricDelta, compare_retest_reports
from .schema import (
    AuditRun,
    ClaimRecord,
    CitationRecord,
    DiagnosisRecord,
    EngineSample,
    EvidenceGraph,
    MetricTrace,
    MentionRecord,
    OptimizationTask,
    PageSnapshot,
    PromptRecord,
    RecommendationRecord,
    RetestRecord,
    SkillOutcomeRecord,
    build_evidence_graph,
)
from .source_classifier import ClassifiedSource, classify_source, classify_sources

__all__ = [
    "AnswerCredentialRef",
    "AnswerProviderConfig",
    "AnswerProviderRequest",
    "OpenAICompatibleAnswerProvider",
    "ArtifactSafetyFinding",
    "ArtifactSafetyReport",
    "assert_artifacts_safe",
    "scan_artifacts_for_access_leaks",
    "AuditArtifacts",
    "AuditRunner",
    "BrowserCaptureArtifact",
    "BrowserCaptureError",
    "BrowserCaptureRecord",
    "BrowserViewport",
    "artifact_digest",
    "make_capture_artifact",
    "CitationAbsorptionMetric",
    "calculate_citation_absorption",
    "calculate_citation_absorption_from_urls",
    "CitationParserError",
    "ParsedCitation",
    "citation_domain",
    "normalize_citation_url",
    "parse_citations",
    "ClaimFidelityResult",
    "audit_claim_fidelity",
    "audit_claims_fidelity",
    "ClassifiedSource",
    "classify_source",
    "classify_sources",
    "CrawlProviderError",
    "CrawlProviderRequest",
    "CrawlProviderResult",
    "StaticCrawlerProvider",
    "pages_from_crawl_result",
    "CrawlerProviderV2Request",
    "CrawlerProviderV2Result",
    "PageCrawlResult",
    "StaticCrawlerProviderV2",
    "ExtractedFAQ",
    "ExtractedPageSnapshot",
    "ExtractedTable",
    "PageSnapshotExtractionError",
    "extract_page_snapshot",
    "EntityProfile",
    "EntityProfileValidationError",
    "ValidationIssue",
    "validate_entity_profile",
    "EvidenceStore",
    "ReportArtifact",
    "FailureDiagnosis",
    "diagnose_failure_v2",
    "FixturePackageResult",
    "run_fixture_package",
    "OptimizationOutcomeRecord",
    "OptimizationOutcomeSummary",
    "recommended_learning_actions",
    "summarize_outcomes",
    "ManualImportError",
    "ManualImportResult",
    "validate_manual_import",
    "ManualImportProvider",
    "ManualImportProviderRequest",
    "ManualImportProviderResult",
    "ProviderStatusCopy",
    "provider_report_status_line",
    "provider_status_copy",
    "ApiKeySession",
    "ApiKeySessionStore",
    "ProviderAccessError",
    "ProviderConnection",
    "ProviderDefinition",
    "ProviderRegistry",
    "default_provider_registry",
    "redact_credential_label",
    "AuthorizationSessionStore",
    "AuthorizationStart",
    "FakeAuthorizationProvider",
    "TokenSession",
    "ProviderOutputEvalCase",
    "ProviderOutputEvalResult",
    "ProviderOutputEvalSummary",
    "evaluate_provider_output_cases",
    "provider_response_to_run",
    "INTENT_TYPES",
    "QueryRecord",
    "build_query_space",
    "RecordedAuditDataset",
    "RecordedDatasetError",
    "load_recorded_dataset",
    "load_recorded_dataset_from_mapping",
    "RetestComparison",
    "RetestMetricDelta",
    "compare_retest_reports",
    "AuditRun",
    "ClaimRecord",
    "CitationRecord",
    "DiagnosisRecord",
    "EngineSample",
    "EvidenceGraph",
    "MetricTrace",
    "MentionRecord",
    "OptimizationTask",
    "PageSnapshot",
    "PromptRecord",
    "RecommendationRecord",
    "RetestRecord",
    "SkillOutcomeRecord",
    "build_evidence_graph",
]
